# Generated by Django 4.1.7 on 2023-07-22 19:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import djbooks.helpers
import djbooks.models
import functools
import taggit.managers


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('taggit', '0005_auto_20220424_2025'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('names', models.CharField(max_length=20)),
                ('last_names', models.CharField(max_length=20)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=20)),
                ('street_address', models.CharField(max_length=100)),
                ('shipping_country', models.CharField(max_length=100)),
                ('shipping_city', models.CharField(max_length=100)),
                ('shipping_zip', models.CharField(max_length=100)),
                ('address_type', models.CharField(choices=[('B', 'Billing'), ('S', 'Shipping')], max_length=1)),
                ('default', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Addresses',
            },
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('author', models.CharField(max_length=30)),
                ('editorial', models.CharField(blank=True, max_length=30)),
                ('edition', models.CharField(blank=True, max_length=20)),
                ('year', models.CharField(blank=True, max_length=4)),
                ('price', models.FloatField(blank=True, default=0)),
                ('discount_price', models.FloatField(blank=True, null=True)),
                ('cover', models.ImageField(blank=True, default='djbooks/static/assets/images/inner-page/category/1.jpg', upload_to=djbooks.models.book_cover_path)),
                ('back', models.ImageField(blank=True, default='djbooks/static/assets/images/inner-page/category/1.jpg', null=True, upload_to=djbooks.models.book_back_path)),
                ('description', models.TextField(blank=True, default=None, null=True)),
                ('condition', models.TextField(blank=True, default=None, null=True)),
                ('stock', models.IntegerField(default=1)),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('image', models.ImageField(default='djbooks/static/assets/images/inner-page/banner.jpg', null=True, upload_to=djbooks.models.category_path)),
                ('slug', models.SlugField(blank=True, max_length=40)),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('charge_id', models.CharField(max_length=50)),
                ('amount', models.FloatField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('payment_method', models.CharField(choices=[('PP', 'Paypal'), ('MP', 'Mercado Pago')], max_length=2)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OrderBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordered', models.BooleanField(default=False)),
                ('quantity', models.IntegerField(default=1)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='djbooks.book')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ref_code', models.CharField(blank=True, max_length=20, null=True)),
                ('start_date', models.DateTimeField(auto_now_add=True)),
                ('ordered_date', models.DateTimeField()),
                ('paid', models.BooleanField(default=False)),
                ('ordered', models.BooleanField(default=False)),
                ('being_delivered', models.BooleanField(default=False)),
                ('received', models.BooleanField(default=False)),
                ('shipping_option', models.CharField(choices=[('dhl', 'DHL'), ('sepomex', 'SEPOMEX'), ('local_pickup', 'Entrega directa')], max_length=12, null=True)),
                ('items', models.ManyToManyField(to='djbooks.orderbook')),
                ('shipping_address', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shipping_address', to='djbooks.address')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ExtraImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to=functools.partial(djbooks.helpers.upload_extra_img, *(), **{'path': 'static/assets/books/'}))),
                ('book', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='djbooks.book')),
            ],
        ),
        migrations.AddField(
            model_name='book',
            name='category',
            field=models.ManyToManyField(to='djbooks.category'),
        ),
        migrations.AddField(
            model_name='book',
            name='related_books',
            field=models.ManyToManyField(blank=True, to='djbooks.book'),
        ),
        migrations.AddField(
            model_name='book',
            name='tags',
            field=taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
