# Generated by Django 4.2.4 on 2023-08-29 22:45

from django.conf import settings
from django.db import migrations, models
import djbooks.models
from djbooks.models import Category

def create_data(apps, schema_editor):
    obj, created = Category.objects.get_or_create(name="Ciudad de México")
    if created:
        obj.save()

def delete_data(apps, schema_editor):
    Category.objects.filter(name="Ciudad de México").delete()

class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('djbooks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='users_wishlist',
            field=models.ManyToManyField(blank=True, related_name='user_wishlist', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='extraimage',
            name='back',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='extraimage',
            name='cover',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='book',
            name='back',
            field=models.ImageField(blank=True, null=True, upload_to=djbooks.models.book_back_path),
        ),
        migrations.RunPython(create_data, delete_data, elidable=True),
    ]
